// import { app, shell, BrowserWindow, ipcMain, globalShortcut } from 'electron'
// import { join } from 'path'
// import { electronApp, optimizer, is } from '@electron-toolkit/utils'
// import { buildMenu } from './menu'
// import icon from '../../resources/icon.png?asset'
import './window'